### PR TITLE
Callback

### PR DESCRIPTION
**Pull request by alahammad**
update gradle.
add otp finished callback.

### CODE REVIEW

**Comment by alahammad** [comment]
@mukeshsolanki can merge my pull request and update your library.

**Comment by mukeshsolanki** [comment]
@alahammad can you update this pr

**Comment by mukeshsolanki** [comment]
Can you update your branch with the latest master @alahammad

**Comment by mukeshsolanki** [comment]
@alahammad don't remove the whole class and add the old one? that simply does not work you have not merged the master branch properly

**Comment by alahammad** [comment]
@mukeshsolanki  my apologies for that, I fixed the issues.

**Comment by mukeshsolanki** [comment]
@alahammad you have not fixed the issue rather just replaced the latest version with the old version of the library

**Comment by mukeshsolanki** [comment]
we now support `app:length="4"` which according to you pr does not exist your targeting an older version of the lib

**Comment by alahammad** [comment]
@mukeshsolanki  no I added callback for pinview, check the code.

**Comment by mukeshsolanki** [comment]
you pulled the latest code and removed all my code which supports dynamic otp size. the new lib does not have ```private EditText mOtpOneField, mOtpTwoField, mOtpThreeField, mOtpFourField```
the new lib has `private List<EditText> editTexts = new ArrayList<>();`

**Comment by alahammad** [comment]
Sorry for that, I cloned your repo before dynamic pins.
Can you add the callback for pin-views after the user fills the pins.

**Comment by mukeshsolanki** [comment]
yeah ill do that and release in the next version

**Pull request closed without merging**
