### PR TITLE
Replace OnOtpCompletionListener with OnOtpTextChangeListener

### PR DESCRIPTION
**Pull request by Janekxyz**
Replace onCompleteListener to be more aware of otp changes. This change also give availability to detect character remove.

### CODE REVIEW

**Review by mukeshsolanki — COMMENTED** [review]
What purpose would this serve??

**Comment by Janekxyz** [comment]
@mukeshsolanki 

This change gives user ability to detect changes e.g. character remove.  Thanks to that change user will be able to detect single change.

I think it gives more ways to interact with this library especially when you need to do something on single change.

**Comment by rmaming** [comment]
I think this feature is what i am looking for. When will this be available?

**Comment by mukeshsolanki** [comment]
There is no need for this you can simply add a text watcher to achieve this,

**Comment by PembaTamang** [comment]
textwatcher is not working for me what could be the problem ?

**Pull request closed without merging**
